// Code generated by goctl. DO NOT EDIT!
// Source: sys.proto

package sysclient

import (
	"context"

	"zero-admin-learn/rpc/sys/sys"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = sys.Request
	Response = sys.Response

	Sys interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultSys struct {
		cli zrpc.Client
	}
)

func NewSys(cli zrpc.Client) Sys {
	return &defaultSys{
		cli: cli,
	}
}

func (m *defaultSys) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
